# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541daf68e247be4da7fbe1ff915a77d9dad4d7d657f4f548431cd5666b2eb64f40e0a4a28d9d71070d962d206cbf0f794fd8e0a2cb815d3b8a0e3f9ba2eb793c

test:
  secret_key_base: 5261dc3a140b27220b69b3357fd216e2332d5d127b9acfe56dd9237250546a97a13f0f783a7b8f9201925e8b9c265c5de1df115adf17f02432a4db1db442fa97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
